apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data: 
  service.webhook.slack: |
    url: https://hooks.slack.com/services/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
    headers:
      - name: Content-Type
        value: application/json
  context: |
    argourl: htttp://192.168.10.140:31500/
  template.app-sync-status: |
    webhook: 
      slack:
        method: POST
    # message: |
    #   Application {{.app.metadata.name}} sync is {{.app.status.sync.status}}.
    #   Application details: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}.
        body: |
         {
           "attachments": [{
             "title": "{{.app.metadata.name}}",
             "title_link": "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}",
             "color": "#18be52",
             "fields": [{
               "title": "Sync Status",
               "value": "{{.app.status.sync.status}}",
               "short": true
             }, {
               "title": "Repository",
               "value": "{{.app.spec.source.repoURL}}",
               "short": true
             }]
           }]
         }
  trigger.on-deployed: |
    when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy'
    oncePer: app.status.sync.revision
    send: [app-sync-succeeded]
  trigger.on-health-degraded: |
    when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy'
    oncePer: app.status.sync.revision
    send: [app-sync-succeeded]
  subscriptions: |
    - recipients:
      - slack
      triggers:
      - on-deployed
      - on-health-degraded